#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml #???resources
    - classpath*:com/**/mapper/*.xml #scr/main/java
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#showSql
server:
  port: 8099